spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: HITwh352@
    url: jdbc:mysql://47.93.124.212:3306/mall?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  redis:
    host: 47.93.124.212
    port: 6379
  rabbitmq:
    addresses: 47.93.124.212
    port: 5672
    username: root
    password: 1234
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
server:
  servlet:
    session:
      timeout: 1800
  port: 8081

